crawling_ftesting:
    resource: "@CrawlingFtestingBundle/Resources/config/routing.yml"
    prefix:   /

users_routing:
    resource: "@ApiBundle/Resources/config/routing.yml"
    defaults: { _format: json }
